# Capstone Project - The Battle of Neighborhoods (Second Week / Course Week 5)

Instructions (The Final Deliverables) 

In this week, you will continue working on your capstone project. Please remember by the end of this week, you will need to submit the following:

1.  A full report consisting of all of the following components (15 marks):
* Introduction where you discuss the business problem and who would be interested in this project.
* Data where you describe the data that will be used to solve the problem and the source of the data.
* Methodology section which represents the main component of the report where you discuss and describe any exploratory data analysis that you did, any inferential statistical testing that you performed, if any, and what machine learnings were used and why.
* Results section where you discuss the results.
* Discussion section where you discuss any observations you noted and any recommendations you can make based on the results.
* Conclusion section where you conclude the report.

2. A link to your Notebook on your Github repository pushed showing your code. (15 marks)

3. Your choice of a presentation or blogpost. (10 marks)

## TABLE OF CONTENTS

* [Introduction: Business Problem](#introduction) 
* [Data](#data)
* [Methodology](#methodology)
* [Analysis](#analysis)
* [Results and Discussion](#results)
* [Discussion](#discussion)
* [Conclusion](#conclusion)
<br>
<br>

## Introduction: Business Problem <a name="introduction"></a>

**Description of the problem:**
  
  For this data science problem, we will explore on how a "Restaurant Guide App" improve consumer experience by answering the question;
  Does the two-factor (Rating and Price) approach sufficient to recommend a venue ?

**Target audience description:**

  To help a group of stakeholders further solve the problem, we will address "Cuisine Connoisseurs, Food Enthusiast and Bloggers" who constantly use restaurant guide app for ease of use.
  
**Discussion on why our Target audience care about the problem:**
 
 Everything today is accessible by means of smart phones. In the food industry, Cuisine Connoisseurs, Food Enthusiast and Bloggers wants a quick easy way to access venue information. They often want straightforward details without the hassle of too much unnecessary data to influence their decision. Now, how do we improve these experience? Why should they care about the two-factor approach in this data science problem? - The minimalistic comparison data use, which is combining Rating and Price will give our targeted audience better insight in finding great budget-friendly restaurants in downtown areas.
<br>
<br>

## Data Section <a name="data"></a>

**Description of the data:** 

  The data sets generated in this **Data Section** is to provide insights on our proposed problem. We will focus mainly on Downtown Toronto. First, we will get the Latitude and Longitude value of our approximate defined center, which is the downtown area. We then define a query to search within our desired range and limit for restaurant venues using Foursquare API. Respectively, by making calls to the API, we can get the Restaurant Rating and Price. Using Folium plotting library we can visualize our map of the downtown area.

**Other datasets in combination with the Foursquare location data:**

  We will enter coordinates generated from the API for our downtown area to google maps. In doing so, we can pinpoint an address for our approximate defined center and further test venue location accuracy and other information. Also, in combination with Foursquare location data, a 'csv file' that depict Rating and Price will be created from the dataset results.

**Examples of the data:**

* Foursquare Credentials and Version
* The geographical coordinate of Downtown Toronto are 43.6563221, -79.3809161.
* The specific venue category : radius = 500; limit = 10
* JSON file for our dataframe
* Venues_map using folium.Map
* Restaurants IDs using https://api.foursquare.com/v2/venues

**Using Data to solve the problem:**
  
  With the generated Data, we can make selection of existing restaurant in any category. The map visualization will be use to show the distance of the restaurants within the neighborhood. Part of the JSON file is significant in examining our calls to Foursquare API and to transform our dataframe for analysis. Relatively, making calls to Foursquare location data will get our given values to make our comparison. Eventually, this dataset results will help us solve the question if our two-factor (Rating and Price) approach sufficient to recommend a venue.  

#### Codes <a name="data"></a>

**Import necessary Libraries:**

In [1]:
import requests # library to handle requests
import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner
import random # library for random number generation

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library

print('Folium installed')
print('Libraries imported.')

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.8.0

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.8.0

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

Folium installed
Libraries imported.


#### Define Foursquare Credentials and Version

In [2]:
CLIENT_ID = '2IFJ4OSQ4YRJ4ZF2BZZQXUNDJSNK4F4JHIFZ2RUVKVZ2FPQH' # your Foursquare ID
CLIENT_SECRET = 'FFJNCIUYMDQFICJLZMSZATWNHBBZCTCCZLRLUU1Z3JYSXNIS' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 10
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: 2IFJ4OSQ4YRJ4ZF2BZZQXUNDJSNK4F4JHIFZ2RUVKVZ2FPQH
CLIENT_SECRET:FFJNCIUYMDQFICJLZMSZATWNHBBZCTCCZLRLUU1Z3JYSXNIS


In [3]:
# Use geopy library to get the latitude and longitude values of Downtown Toronto

address = 'Downtown Toronto, ON'
geolocator = Nominatim(user_agent="Downtown_Toronto_explorer")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Downtown Toronto are {}, {}.'.format(latitude, longitude))

The geograpical coordinate of Downtown Toronto are 43.6563221, -79.3809161.


<br>

### The Search for a specific venue

Imagine our targeted audience (Cuisine Connoisseurs, Food Enthusiast and Bloggers) is in a downtown area using the Restaurant Guide App and wanted to find great budget-friendly restaurants. It is a busy town, a quick comparison of several venues in close proximity would be ideal for they're always on the go. 
<br>

In [4]:
# define a query to search for Restaurant within 500 metres from Downtown Toronto

search_query = 'Restaurant'
radius = 500
print(search_query + ' .... OK!')

Restaurant .... OK!


#### Define the corresponding URL and limit = 10

In [5]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=2IFJ4OSQ4YRJ4ZF2BZZQXUNDJSNK4F4JHIFZ2RUVKVZ2FPQH&client_secret=FFJNCIUYMDQFICJLZMSZATWNHBBZCTCCZLRLUU1Z3JYSXNIS&ll=43.6563221,-79.3809161&v=20180604&query=Restaurant&radius=500&limit=10'

#### Make the call to foursquare api; send GET Request and examine results

In [6]:
results = requests.get(url).json()
results


{'meta': {'code': 200, 'requestId': '5df88bb86d8c56001bd7d7a2'},
 'response': {'venues': [{'id': '4ad4c05ff964a52048f720e3',
    'name': 'Hemispheres Restaurant & Bistro',
    'location': {'address': '110 Chestnut Street',
     'lat': 43.65488413420439,
     'lng': -79.38593077371578,
     'labeledLatLngs': [{'label': 'display',
       'lat': 43.65488413420439,
       'lng': -79.38593077371578}],
     'distance': 434,
     'postalCode': 'M5G 1R3',
     'cc': 'CA',
     'city': 'Toronto',
     'state': 'ON',
     'country': 'Canada',
     'formattedAddress': ['110 Chestnut Street',
      'Toronto ON M5G 1R3',
      'Canada']},
    'categories': [{'id': '4bf58dd8d48988d14e941735',
      'name': 'American Restaurant',
      'pluralName': 'American Restaurants',
      'shortName': 'American',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/default_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1576569799',
    'hasPerk': False},
   {'id': '

#### Get relevant part of JSON and transform it into a *pandas* dataframe

In [7]:
# assign relevant part of JSON to venues
venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

id                                 name  \
0  4ad4c05ff964a52048f720e3      Hemispheres Restaurant & Bistro   
1  4edbccaaf9abeea3db5268df        Terrace Restaurant at Elmwood   
2  4c6abb8c2c29d13ad2720e41                               Subway   
3  4b295e10f964a520ba9d24e3  Richtree Natural Market Restaurants   
4  4b2027b5f964a520f82d24e3        Hong Shing Chinese Restaurant   

                                          categories    referralId  hasPerk  \
0  [{'id': '4bf58dd8d48988d14e941735', 'name': 'A...  v-1576569799    False   
1  [{'id': '4bf58dd8d48988d14e941735', 'name': 'A...  v-1576569799    False   
2  [{'id': '4bf58dd8d48988d1c5941735', 'name': 'S...  v-1576569799    False   
3  [{'id': '4bf58dd8d48988d1c4941735', 'name': 'R...  v-1576569799    False   
4  [{'id': '4bf58dd8d48988d145941735', 'name': 'C...  v-1576569799    False   

      location.address  location.lat  location.lng  \
0  110 Chestnut Street     43.654884    -79.385931   
1                  NaN     43.656101    -79.381480   
2      10 Dundas St. E     43.656260    -79.380920   
3        14 Queen St W     43.652614    -79.380231   
4      195 Dundas St W     43.654925    -79.387089   

                             location.labeledLatLngs  location.distance  \
0  [{'label': 'display', 'lat': 43.65488413420439...                434   
1  [{'label': 'display', 'lat': 43.65610066909799...                 51   
2  [{'label': 'display', 'lat': 43.65625998968890...                  6   
3  [{'label': 'display', 'lat': 43.65261436174172...                416   
4  [{'label': 'display', 'lat': 43.65492521335936...                520   

  location.postalCode location.cc location.city location.state  \
0             M5G 1R3          CA       Toronto             ON   
1                 NaN          CA           NaN            NaN   
2             M5B 2G9          CA       Toronto             ON   
3             M5H 3X4          CA       Toronto             ON   
4             M5G 1C7          CA       Toronto             ON   

  location.country                          location.formattedAddress  \
0           Canada  [110 Chestnut Street, Toronto ON M5G 1R3, Canada]   
1           Canada                                           [Canada]   
2           Canada  [10 Dundas St. E (at Yonge St.), Toronto ON M5...   
3           Canada        [14 Queen St W, Toronto ON M5H 3X4, Canada]   
4           Canada  [195 Dundas St W (at University Ave), Toronto ...   

  location.crossStreet venuePage.id  
0                  NaN          NaN  
1                  NaN          NaN  
2         at Yonge St.          NaN  
3                  NaN          NaN  
4    at University Ave     60327598

#### Define information of interest and filter dataframe

In [8]:
# keep only columns that include venue name, and anything that is associated with location
filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term
dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

name            categories  \
0      Hemispheres Restaurant & Bistro   American Restaurant   
1        Terrace Restaurant at Elmwood   American Restaurant   
2                               Subway        Sandwich Place   
3  Richtree Natural Market Restaurants            Restaurant   
4        Hong Shing Chinese Restaurant    Chinese Restaurant   
5   Akashiro Japanese Restaurant & Bar      Sushi Restaurant   
6               The Senator Restaurant                 Diner   
7   Castries Bar & Five Way Restaurant  Caribbean Restaurant   
8           Hendricks Restaurant & Bar            Restaurant   
9         Yueh Tung Chinese Restaurant    Chinese Restaurant   

               address        lat        lng  \
0  110 Chestnut Street  43.654884 -79.385931   
1                  NaN  43.656101 -79.381480   
2      10 Dundas St. E  43.656260 -79.380920   
3        14 Queen St W  43.652614 -79.380231   
4      195 Dundas St W  43.654925 -79.387089   
5        220 Yonge St.  43.655965 -79.380541   
6  249 Victoria Street  43.655641 -79.379199   
7                  NaN  43.654728 -79.380928   
8      Yonge And Queen  43.653415 -79.379698   
9    126 Elizabeth St.  43.655281 -79.385337   

                                      labeledLatLngs  distance postalCode  cc  \
0  [{'label': 'display', 'lat': 43.65488413420439...       434    M5G 1R3  CA   
1  [{'label': 'display', 'lat': 43.65610066909799...        51        NaN  CA   
2  [{'label': 'display', 'lat': 43.65625998968890...         6    M5B 2G9  CA   
3  [{'label': 'display', 'lat': 43.65261436174172...       416    M5H 3X4  CA   
4  [{'label': 'display', 'lat': 43.65492521335936...       520    M5G 1C7  CA   
5  [{'label': 'display', 'lat': 43.65596504293232...        49        NaN  CA   
6  [{'label': 'display', 'lat': 43.65564091455335...       157    M5B 1T8  CA   
7  [{'label': 'display', 'lat': 43.65472793579101...       177        NaN  CA   
8  [{'label': 'display', 'lat': 43.65341542752959...       338    M5G 2H6  CA   
9  [{'label': 'display', 'lat': 43.65528126342919...       374        NaN  CA   

      city state country                                   formattedAddress  \
0  Toronto    ON  Canada  [110 Chestnut Street, Toronto ON M5G 1R3, Canada]   
1      NaN   NaN  Canada                                           [Canada]   
2  Toronto    ON  Canada  [10 Dundas St. E (at Yonge St.), Toronto ON M5...   
3  Toronto    ON  Canada        [14 Queen St W, Toronto ON M5H 3X4, Canada]   
4  Toronto    ON  Canada  [195 Dundas St W (at University Ave), Toronto ...   
5  Toronto    ON  Canada  [220 Yonge St. (in Toronto Eaton Centre Urban ...   
6  Toronto    ON  Canada  [249 Victoria Street (btwn Dundas St E and Shu...   
7      NaN   NaN  Canada                                           [Canada]   
8  Toronto    ON  Canada      [Yonge And Queen, Toronto ON M5G 2H6, Canada]   
9  Toronto    ON  Canada  [126 Elizabeth St. (Dundas St.), Toronto ON, C...   

                            crossStreet                        id  
0                                   NaN  4ad4c05ff964a52048f720e3  
1                                   NaN  4edbccaaf9abeea3db5268df  
2                          at Yonge St.  4c6abb8c2c29d13ad2720e41  
3                                   NaN  4b295e10f964a520ba9d24e3  
4                     at University Ave  4b2027b5f964a520f82d24e3  
5  in Toronto Eaton Centre Urban Eatery  4fbbb3ace4b01e39077b4d55  
6        btwn Dundas St E and Shuter St  4ad7929cf964a520500c21e3  
7                                   NaN  53ae6660498e1ac3c1282743  
8                                   NaN  5a8b24b2018cbb6c4ca70dae  
9                            Dundas St.  52a7ae41498eed3af4d0a3fa

In [9]:
dataframe_filtered.name

0        Hemispheres Restaurant & Bistro
1          Terrace Restaurant at Elmwood
2                                 Subway
3    Richtree Natural Market Restaurants
4          Hong Shing Chinese Restaurant
5     Akashiro Japanese Restaurant & Bar
6                 The Senator Restaurant
7     Castries Bar & Five Way Restaurant
8             Hendricks Restaurant & Bar
9           Yueh Tung Chinese Restaurant
Name: name, dtype: object

<br>

### Map of The City’s Downtown Area 

Would it be convenient if we could show our targeted audience the map of their search. Also this will show them how far they are from a prospective venue.

In [10]:
# Let’s locate the approximate center and explore neighboring restaurants
# Zoom in to visualize
# Note: Github may not display map

venues_map = folium.Map(location=[latitude, longitude], zoom_start=10) # generate map centred around 

# add a red circle marker to represent 
folium.features.CircleMarker(
    [latitude, longitude],
    radius=10,
    color='red',
    popup='Downtown Toronto',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add the restaurants as blue circle markers
for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map

##### Approximate Defined Center: Google Maps

We searched cordinate 43.6563221, -79.3809161 for Downtown Toronto in google maps. Result will shows "418 The PATH - Yonge-Dundas Square, Toronto, ON M5B 1R4, Canada". This is our approximate defined center and represented by a red circle marker from the generated map above. Using the result, we can test venue location accuracy and other information.

#### Dataframe Clean Up

In [11]:
# Let's sort by distance
sort_by_distance = dataframe_filtered.sort_values('distance')
sort_by_distance

name            categories  \
2                               Subway        Sandwich Place   
5   Akashiro Japanese Restaurant & Bar      Sushi Restaurant   
1        Terrace Restaurant at Elmwood   American Restaurant   
6               The Senator Restaurant                 Diner   
7   Castries Bar & Five Way Restaurant  Caribbean Restaurant   
8           Hendricks Restaurant & Bar            Restaurant   
9         Yueh Tung Chinese Restaurant    Chinese Restaurant   
3  Richtree Natural Market Restaurants            Restaurant   
0      Hemispheres Restaurant & Bistro   American Restaurant   
4        Hong Shing Chinese Restaurant    Chinese Restaurant   

               address        lat        lng  \
2      10 Dundas St. E  43.656260 -79.380920   
5        220 Yonge St.  43.655965 -79.380541   
1                  NaN  43.656101 -79.381480   
6  249 Victoria Street  43.655641 -79.379199   
7                  NaN  43.654728 -79.380928   
8      Yonge And Queen  43.653415 -79.379698   
9    126 Elizabeth St.  43.655281 -79.385337   
3        14 Queen St W  43.652614 -79.380231   
0  110 Chestnut Street  43.654884 -79.385931   
4      195 Dundas St W  43.654925 -79.387089   

                                      labeledLatLngs  distance postalCode  cc  \
2  [{'label': 'display', 'lat': 43.65625998968890...         6    M5B 2G9  CA   
5  [{'label': 'display', 'lat': 43.65596504293232...        49        NaN  CA   
1  [{'label': 'display', 'lat': 43.65610066909799...        51        NaN  CA   
6  [{'label': 'display', 'lat': 43.65564091455335...       157    M5B 1T8  CA   
7  [{'label': 'display', 'lat': 43.65472793579101...       177        NaN  CA   
8  [{'label': 'display', 'lat': 43.65341542752959...       338    M5G 2H6  CA   
9  [{'label': 'display', 'lat': 43.65528126342919...       374        NaN  CA   
3  [{'label': 'display', 'lat': 43.65261436174172...       416    M5H 3X4  CA   
0  [{'label': 'display', 'lat': 43.65488413420439...       434    M5G 1R3  CA   
4  [{'label': 'display', 'lat': 43.65492521335936...       520    M5G 1C7  CA   

      city state country                                   formattedAddress  \
2  Toronto    ON  Canada  [10 Dundas St. E (at Yonge St.), Toronto ON M5...   
5  Toronto    ON  Canada  [220 Yonge St. (in Toronto Eaton Centre Urban ...   
1      NaN   NaN  Canada                                           [Canada]   
6  Toronto    ON  Canada  [249 Victoria Street (btwn Dundas St E and Shu...   
7      NaN   NaN  Canada                                           [Canada]   
8  Toronto    ON  Canada      [Yonge And Queen, Toronto ON M5G 2H6, Canada]   
9  Toronto    ON  Canada  [126 Elizabeth St. (Dundas St.), Toronto ON, C...   
3  Toronto    ON  Canada        [14 Queen St W, Toronto ON M5H 3X4, Canada]   
0  Toronto    ON  Canada  [110 Chestnut Street, Toronto ON M5G 1R3, Canada]   
4  Toronto    ON  Canada  [195 Dundas St W (at University Ave), Toronto ...   

                            crossStreet                        id  
2                          at Yonge St.  4c6abb8c2c29d13ad2720e41  
5  in Toronto Eaton Centre Urban Eatery  4fbbb3ace4b01e39077b4d55  
1                                   NaN  4edbccaaf9abeea3db5268df  
6        btwn Dundas St E and Shuter St  4ad7929cf964a520500c21e3  
7                                   NaN  53ae6660498e1ac3c1282743  
8                                   NaN  5a8b24b2018cbb6c4ca70dae  
9                            Dundas St.  52a7ae41498eed3af4d0a3fa  
3                                   NaN  4b295e10f964a520ba9d24e3  
0                                   NaN  4ad4c05ff964a52048f720e3  
4                     at University Ave  4b2027b5f964a520f82d24e3

In [12]:
# Hide the index
sort_by_distance.style.hide_index()

#### Explore Restaurants using their ID

In [13]:
# Making calls to Foursquare API to get 'given values'
# The Senator Restaurant would be our pilot call
# We then get the Rating, Price, Tier and Currency for others

In [14]:
venue_id = '4ad7929cf964a520500c21e3' # ID of The Senator Restaurant
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)
url

'https://api.foursquare.com/v2/venues/4ad7929cf964a520500c21e3?client_id=2IFJ4OSQ4YRJ4ZF2BZZQXUNDJSNK4F4JHIFZ2RUVKVZ2FPQH&client_secret=FFJNCIUYMDQFICJLZMSZATWNHBBZCTCCZLRLUU1Z3JYSXNIS&v=20180604'

In [15]:
result = requests.get(url).json()
print(result['response']['venue'].keys())
result['response']['venue']



dict_keys(['id', 'name', 'contact', 'location', 'canonicalUrl', 'categories', 'verified', 'stats', 'url', 'price', 'likes', 'dislike', 'ok', 'rating', 'ratingColor', 'ratingSignals', 'allowMenuUrlEdit', 'beenHere', 'specials', 'photos', 'venuePage', 'reasons', 'description', 'storeId', 'page', 'hereNow', 'createdAt', 'tips', 'shortUrl', 'timeZone', 'listed', 'hours', 'popular', 'pageUpdates', 'inbox', 'attributes', 'bestPhoto', 'colors'])


{'id': '4ad7929cf964a520500c21e3',
 'name': 'The Senator Restaurant',
 'contact': {'phone': '4163647517',
  'formattedPhone': '(416) 364-7517',
  'twitter': 'thesenatorto',
  'facebook': '566290650069193',
  'facebookUsername': 'thesenatorto',
  'facebookName': 'The Senator'},
 'location': {'address': '249 Victoria Street',
  'crossStreet': 'btwn Dundas St E and Shuter St',
  'lat': 43.65564091455335,
  'lng': -79.37919882575557,
  'labeledLatLngs': [{'label': 'display',
    'lat': 43.65564091455335,
    'lng': -79.37919882575557}],
  'postalCode': 'M5B 1T8',
  'cc': 'CA',
  'city': 'Toronto',
  'state': 'ON',
  'country': 'Canada',
  'formattedAddress': ['249 Victoria Street (btwn Dundas St E and Shuter St)',
   'Toronto ON M5B 1T8',
   'Canada']},
 'canonicalUrl': 'https://foursquare.com/v/the-senator-restaurant/4ad7929cf964a520500c21e3',
 'categories': [{'id': '4bf58dd8d48988d147941735',
   'name': 'Diner',
   'pluralName': 'Diners',
   'shortName': 'Diner',
   'icon': {'prefix': 'h

In [16]:
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

7.9


In [17]:
try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')    

{'tier': 2, 'message': 'Moderate', 'currency': '$'}


In [18]:
# Now we leverage the Foursquare location data to the fullest
# let's get the Rating, Price, Tier and Currency for other restaurants


venue_id = '4c6abb8c2c29d13ad2720e41' # Subway
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.') 
    
    
venue_id = '4fbbb3ace4b01e39077b4d55' # Akashiro Japanese Restaurant & Bar
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.') 
    
        
venue_id = '4edbccaaf9abeea3db5268df' # Terrace Restaurant at Elmwood
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')
    
    
venue_id = '539c6f13498e06f4cc765165' # The Elm Tree Restaurant
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')
    
    
venue_id = '5a8b24b2018cbb6c4ca70dae' # Hendricks Restaurant & Bar
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')
    

venue_id = '4ae4b055f964a520229d21e3' # Kyoto House Japanese Restaurant
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')
    

venue_id = '52a7ae41498eed3af4d0a3fa' # Yueh Tung Chinese Restaurant
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')

venue_id = '4b295e10f964a520ba9d24e3' # Richtree Natural Market Restaurants
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')


venue_id = '4ad4c05ff964a52048f720e' # Hemispheres Restaurant & Bistro
url = 'https://api.foursquare.com/v2/venues/{}?client_id={}&client_secret={}&v={}'.format(venue_id, CLIENT_ID, CLIENT_SECRET, VERSION)

result = requests.get(url).json()
try:
    print(result['response']['venue']['rating'])
except:
    print('This venue has not been rated yet.')

try:
    print(result['response']['venue']['price'])
except:
    print('No Details.')


5.7
{'tier': 1, 'message': 'Cheap', 'currency': '$'}
5.4
{'tier': 2, 'message': 'Moderate', 'currency': '$'}
This venue has not been rated yet.
{'tier': 2, 'message': 'Moderate', 'currency': '$'}
8.3
No Details.
6.1
{'tier': 2, 'message': 'Moderate', 'currency': '$'}
5.9
{'tier': 2, 'message': 'Moderate', 'currency': '$'}
7.8
{'tier': 1, 'message': 'Cheap', 'currency': '$'}
6.2
{'tier': 2, 'message': 'Moderate', 'currency': '$'}
This venue has not been rated yet.
No Details.


##### Dataset Results above were extracted to csv format

In [19]:
# Let's get the csv file to create new dataframe
df_dtres = pd.read_csv('DT_Res_final.csv')
df_dtres

Restaurant Rating      Price
0                               Subway     5.7     Cheap
1   Akashiro Japanese Restaurant & Bar     5.4  Moderate
2        Terrace Restaurant at Elmwood      NR  Moderate
3               The Senator Restaurant     7.9  Moderate
4              The Elm Tree Restaurant     8.3        ND
5           Hendricks Restaurant & Bar     6.1  Moderate
6      Kyoto House Japanese Restaurant     5.9  Moderate
7         Yueh Tung Chinese Restaurant     7.8     Cheap
8  Richtree Natural Market Restaurants     6.2  Moderate
9      Hemispheres Restaurant & Bistro      NR        ND

##### New Dataframe: Rating and Price

In [20]:
# Look for word 'Cheap'
df_word=df_dtres[df_dtres['Price'].str.contains('Cheap')].reset_index(drop=True)

# Hide the index
df_word.style.hide_index()

### Table 1

In [21]:
# Look for word 'Moderate'
df_word=df_dtres[df_dtres['Price'].str.contains('Moderate')].reset_index(drop=True)

# Hide the index
df_word.style.hide_index()

### Table 2
<br>
<br>

## Methodology Section <a name="methodology"></a>

In our Business Problem section, we introduced whether our Restaurant Guide App would be sufficient to recommend a venue focusing only within the Rating and Price. Consequently, from our Data Section, we explained how our datasets were used in solving the business problem. For our **data requirements**, we showed that we need both traditional and non-traditional datasets. Mainly leveraging Foursquare Location Data in conjunction with google maps and 'csv file' created from the dataset results. Relatively from the **collected data**, we have identified all sources and how they were extracted. Thus, providing us with better **understanding and preparation** on how to execute our data science problem. Using data visualization, we have created our **modeling and evaluation** for the Restaurant Guide App (Two-Factor Approach).  We have seen the correlations between cleaning up our unstructured and structured datasets to generate our minimalistic results.
<br>
<br>

## Analysis Section <a name="analysis"></a> 

Stakeholders had to consider the Two-Factor Approach to improve their consumer experience. However, would the gathered datasets enough to deploy this concept? Simple answer is, yes. Let’s **analyze** the "Restaurant Guide App" (Two-Factor Approach);
Virtually, Table 1 and 2 shows enough data without overwhelming our targeted audience. Cuisine Connoisseurs, Food Enthusiast and Bloggers, who constantly use restaurant guide app for quick venue information, will appreciate this minimalistic comparison. Stakeholders have to consider the two-factor approach for improvement of consumer experience. Developers then can collaborate and utilize the datasets to come up with ways to show the Tables as part of the app. Sometimes, less can influence significant decisions but not to sacrifice functionality. Here, the Rating and Price is sufficient to recommend a venue. Our tables show us, " Yueh Tung Chinese Restaurant and The Senator Restaurant" as our top picks.
<br>
Based on the new dataframe and with less programming, we see the Rating and Price category influenced our decisions. Here, we show that the categories pulled our preferred restaurants in the downtown areas. Again, without being explicit, we can predict a restaurant with virtually has the most complete values across the board be our top picks. Thus, improve consumer experience. We also have relied on the patterns of our sub categories (Cheap and Moderate) to build our statistical model.
<br>
<br>

## Results Section <a name="results"></a> 

Utilizing all identified sources for our data we can make adjustments to our Two-Factor Approach model upon deployment if needed. Moreover, the predictivenes (virtual comparison) of our model can be fine-tuned using the dataset results.  Stakeholders can benefit from its simplicity to refine known testing outcome. Most importantly, with an improved consumer experience in place, it will open opportunities  for constructive feedback to re-evaluate efficiency of our Restaurant Guide App. As we can virtually  see from the tables, we had analyzed our top picks and answered the main question to the data science problem in our data section.
<br>
<br>

## Discussion Section <a name="discussion"></a> 

Based on the results, even if we leverage the power of Foursquare Location Data to the fullest, external sources can indeed provide a much adequate visualization. Using basic google map search pinpoint our downtown area and approximately test the distance of our neighborhood restaurants. The spreadsheet manipulation we have created for our new dataframe simplified the dataset results and became grounds for comparison. Realistically provided insights that the Two-Factor Approach (Rating and Price) is sufficient to recommend a venue. As previously mentioned, “Sometimes, less can influence significant decisions but not to sacrifice functionality”. With that in mind, to clean these data is not necessarily mean to disregard parts of dataset result. Every code plays a vital part in providing our targeted audience an improve consumer experience. The minimalistic functional comparison assisted our stakeholders to better understand the impact in developing the Restaurant Guide App. As Data Scientist, it is recommended that all datasets, structured or unstructured should be put in consideration. 
<br>
<br>

## Conclusion Section <a name="discussion"></a> 

Finally, can we deploy the model into practice? Yes, the proprietary "Restaurant Guide App" (Two-Factor Approach) model is predictive. Therefore, can be revaluated, refine adjustments and apply testing to known outcome.  Our model is leverage through the power of Foursquare Location Data and external resources.  Hence, we can solve real world issues pertaining to our  data science problem.  We can now be  more competitive in today’s  market trend by polishing  our dataset to improve consumer experience.